---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eac3-converter-config
  namespace: eac3-converter
data:
  TZ: "Europe/Paris"
  DEBUG_MODE: "false"
  START_TIME: "04:00"
  RUN_IMMEDIATELY: "false"
  FFMPEG_BITRATE_STEREO: "384k"
  FFMPEG_BITRATE_SURROUND: "1536k"
  FFMPEG_BITRATE_SURROUND_PLUS: "1664k"
  FFMPEG_DIALNORM: "-27"
  FFMPEG_MIXING_LEVEL: "80"
  FFMPEG_STRICT_MODE: "-2"
  FFMPEG_FLAGS: "+genpts"
  FFMPEG_TIMEOUT_SECONDS: "3600"
  FFMPEG_MIN_DISK_SPACE_RATIO: "1.5"
  FFMPEG_THREADS: "0"
  FFMPEG_BUFSIZE: "128k"
  FFMPEG_PERFORMANCE_FLAGS: "+discardcorrupt+genpts+igndts+ignidx"
  FFMPEG_AVOID_NEGATIVE_TS: "make_zero"
  FFMPEG_MAX_MUXING_QUEUE_SIZE: "1024"
