apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eac3-converter-cache
  namespace: eac3-converter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Adjust according to your cluster
